"""
Exercise 5B: Kronecker Graphs using NumPy and NetworkX

Topics Covered (from Network Science thread):
- Kronecker Product for graph generation
- Self-similarity in networks
- Adjacency matrix construction
- Graph properties: degree distribution, clustering, components
- NetworkX analysis
- Graph visualization

Based on:
- Network Science lectures (Kronecker Graphs section)
- Self-similarity concept: small patterns repeat at larger scales
- Used as synthetic models for social, communication, and internet-like networks
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from collections import Counter

# ==========================================================
# SECTION 1: KRONECKER GRAPH THEORY (from thread discussions)
# ==========================================================

print("="*70)
print("EXERCISE 5B: KRONECKER GRAPHS")
print("="*70)

print("\nKey Concepts from Network Science Lectures:")
print("• Kronecker graphs exhibit self-similarity")
print("• Small patterns repeat at larger scales")
print("• Generated by recursive Kronecker product")
print("• Often used as synthetic models for social,")
print("  communication, and internet-like networks")

# ==========================================================
# SECTION 2: CREATE INITIATOR MATRIX
# ==========================================================

print("\n" + "="*70)
print("SECTION 1: INITIATOR MATRIX")
print("="*70)

# Standard initiator matrix for graph generation
K1 = np.array([
    [1, 1],
    [1, 0]
], dtype=int)

print("\nInitiator Matrix (K1) - 2×2 pattern:")
print(K1)
print("\nInterpretation:")
print("  [1,1] → Edge exists between these positions")
print("  [1,0] → Asymmetric connection pattern")

# ==========================================================
# SECTION 3: KRONECKER PRODUCT EXPANSION
# ==========================================================

print("\n" + "="*70)
print("SECTION 2: KRONECKER PRODUCT EXPANSION")
print("="*70)

# Level 1: Original 2×2 matrix
print("\nLevel 1: K1 (2×2 matrix)")
print(K1)

# Level 2: First Kronecker product
K2 = np.kron(K1, K1)
print(f"\nLevel 2: K2 = K1 ⊗ K1 ({K2.shape[0]}×{K2.shape[1]} matrix)")

# Level 3: Second Kronecker product (for reasonable-sized graph)
K3 = np.kron(K2, K1)
print(f"\nLevel 3: K3 = K2 ⊗ K1 ({K3.shape[0]}×{K3.shape[1]} matrix)")

# Show size progression
print("\nMatrix Size Progression:")
print(f"  K1: {K1.shape[0]}×{K1.shape[1]} = {K1.shape[0]*K1.shape[1]} cells")
print(f"  K2: {K2.shape[0]}×{K2.shape[1]} = {K2.shape[0]*K2.shape[1]} cells")
print(f"  K3: {K3.shape[0]}×{K3.shape[1]} = {K3.shape[0]*K3.shape[1]} cells")

# ==========================================================
# SECTION 4: CREATE NETWORKX GRAPH
# ==========================================================

print("\n" + "="*70)
print("SECTION 3: NETWORKX GRAPH CREATION")
print("="*70)

# Convert Kronecker matrix to graph (undirected)
G = nx.from_numpy_array(K3)

print(f"\nGraph created from K3:")
print(f"  Graph type: {type(G).__name__}")
print(f"  Number of nodes: {G.number_of_nodes()}")
print(f"  Number of edges: {G.number_of_edges()}")

# Check if graph is connected
is_connected = nx.is_connected(G)
print(f"  Graph is connected: {is_connected}")

# ==========================================================
# SECTION 5: DEGREE ANALYSIS
# ==========================================================

print("\n" + "="*70)
print("SECTION 4: DEGREE ANALYSIS")
print("="*70)

# Compute all degrees
degrees = [degree for node, degree in G.degree()]

print(f"\nDegree Statistics:")
print(f"  Minimum degree: {min(degrees)}")
print(f"  Maximum degree: {max(degrees)}")
print(f"  Average degree: {np.mean(degrees):.2f}")
print(f"  Median degree: {np.median(degrees):.0f}")
print(f"  Standard deviation: {np.std(degrees):.2f}")

# Degree distribution
print(f"\nDegree Distribution:")
degree_counts = Counter(degrees)
for degree in sorted(degree_counts.keys()):
    count = degree_counts[degree]
    percentage = (count / len(degrees)) * 100
    bar = "█" * int(percentage / 2)  # Simple histogram bar
    print(f"  Degree {degree:2d}: {count:3d} nodes ({percentage:5.1f}%) {bar}")

# Degree distribution inspection (corrected from power-law claim)
print("\nDegree Distribution Inspection:")
print("  Kronecker graphs often produce degree distributions")
print("  that resemble heavy-tailed distributions found in")
print("  real-world networks (social, internet, biological).")
print("  Formal power-law testing would require:")
print("    - Fitting a power-law model")
print("    - Goodness-of-fit tests (e.g., Kolmogorov-Smirnov)")
print("    - Comparison with alternative distributions")
print(f"\n  Observed: max/mean ratio = {max(degrees)/np.mean(degrees):.2f}")
print("  (Suggests broad distribution, but not definitive proof)")

# ==========================================================
# SECTION 6: CONNECTED COMPONENTS
# ==========================================================

print("\n" + "="*70)
print("SECTION 5: CONNECTED COMPONENTS")
print("="*70)

components = list(nx.connected_components(G))
print(f"\nNumber of connected components: {len(components)}")

if len(components) == 1:
    print("✓ Graph is fully connected (single component)")
    print("  This demonstrates the 'giant component' property")
else:
    print("Multiple components found:")
    component_sizes = sorted([len(c) for c in components], reverse=True)
    for i, size in enumerate(component_sizes[:5], 1):
        print(f"  Component {i}: size = {size}")

# Largest connected component
largest_comp = max(components, key=len)
print(f"\nLargest component size: {len(largest_comp)} nodes")
print(f"Fraction in largest component: {len(largest_comp)/G.number_of_nodes():.1%}")

# ==========================================================
# SECTION 7: CLUSTERING ANALYSIS
# ==========================================================

print("\n" + "="*70)
print("SECTION 6: CLUSTERING COEFFICIENT")
print("="*70)

# Local clustering for each node
clustering_coeffs = nx.clustering(G)

print(f"\nClustering Coefficient Statistics:")
print(f"  Average clustering: {np.mean(list(clustering_coeffs.values())):.4f}")
print(f"  Min clustering: {min(clustering_coeffs.values()):.4f}")
print(f"  Max clustering: {max(clustering_coeffs.values()):.4f}")

# Sample clustering values
print(f"\nSample node clustering coefficients (first 5 nodes):")
sample_nodes = list(range(min(5, G.number_of_nodes())))
for node in sample_nodes:
    print(f"  Node {node}: C = {clustering_coeffs[node]:.4f}")

# Transitivity (global clustering)
transitivity = nx.transitivity(G)
print(f"\nGlobal clustering (transitivity): {transitivity:.4f}")

# ==========================================================
# SECTION 8: SHORTEST PATHS (if graph is small enough)
# ==========================================================

print("\n" + "="*70)
print("SECTION 7: SHORTEST PATH ANALYSIS")
print("="*70)

if is_connected and G.number_of_nodes() <= 20:
    # Calculate diameter
    diameter = nx.diameter(G)
    print(f"\nGraph diameter: {diameter}")
    
    # Calculate average path length
    avg_path_length = nx.average_shortest_path_length(G)
    print(f"Average shortest path length: {avg_path_length:.3f}")
    
    # Example path
    source, target = 0, G.number_of_nodes() - 1
    if nx.has_path(G, source, target):
        path = nx.shortest_path(G, source, target)
        print(f"\nExample path (Node {source} → Node {target}):")
        print(f"  Path: {' → '.join(map(str, path))}")
        print(f"  Length: {len(path)-1} steps")
else:
    print(f"\nGraph has {G.number_of_nodes()} nodes")
    if not is_connected:
        print("  Graph is disconnected - using largest component for analysis")
        largest_subgraph = G.subgraph(largest_comp)
        if largest_subgraph.number_of_nodes() > 1:
            print(f"  Diameter of largest component: {nx.diameter(largest_subgraph)}")

# ==========================================================
# SECTION 9: GRAPH PROPERTIES
# ==========================================================

print("\n" + "="*70)
print("SECTION 8: GRAPH PROPERTIES")
print("="*70)

density = nx.density(G)
print(f"\nGraph density: {density:.6f}")
print(f"  (Fraction of possible edges that exist)")

# Theoretical maximum edges
n_nodes = G.number_of_nodes()
max_possible_edges = n_nodes * (n_nodes - 1) / 2
print(f"  Possible edges: {max_possible_edges:.0f}")
print(f"  Actual edges: {G.number_of_edges()}")
print(f"  Sparsity: {(1 - density)*100:.2f}%")

# ==========================================================
# SECTION 10: SELF-SIMILARITY PROPERTY
# ==========================================================

print("\n" + "="*70)
print("SECTION 9: SELF-SIMILARITY PROPERTY")
print("="*70)

print("\nKronecker graphs exhibit self-similarity (from thread):")
print("  • The same 2×2 pattern appears at all scales")
print("  • Degree distribution follows a broad distribution")
print("  • Hierarchical community structure emerges")
print("\nThis self-similarity makes Kronecker graphs useful for:")
print("  • Modeling hierarchical real-world networks")
print("  • Generating test graphs with known properties")
print("  • Understanding network growth processes")

# ==========================================================
# SECTION 11: VISUALIZATION
# ==========================================================

print("\n" + "="*70)
print("SECTION 10: GRAPH VISUALIZATION")
print("="*70)
print("\nGenerating visualizations...")

# Create figure with 2 subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

# Visualization 1: Spring layout
pos1 = nx.spring_layout(G, seed=42, k=2, iterations=50)
nx.draw(G, pos1, ax=ax1, with_labels=True, 
        node_color='lightgreen', node_size=800,
        edge_color='gray', font_size=7, width=1)
ax1.set_title("Kronecker Graph - Spring Layout", fontsize=12, fontweight='bold')

# Visualization 2: Circular layout (shows structure better)
pos2 = nx.circular_layout(G)
nx.draw(G, pos2, ax=ax2, with_labels=True,
        node_color='lightblue', node_size=800,
        edge_color='darkgray', font_size=7, width=1)
ax2.set_title("Kronecker Graph - Circular Layout", fontsize=12, fontweight='bold')

plt.suptitle(f"Kronecker Graph from 2×2 Initiator Matrix\n"
             f"{G.number_of_nodes()} Nodes, {G.number_of_edges()} Edges", 
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Visualization 3: Degree histogram
fig2, ax = plt.subplots(figsize=(10, 6))

degree_counts_sorted = sorted(degree_counts.items())
degrees_plot = [d for d, c in degree_counts_sorted]
counts_plot = [c for d, c in degree_counts_sorted]

ax.bar(degrees_plot, counts_plot, color='skyblue', edgecolor='black', alpha=0.7)
ax.set_xlabel('Degree', fontsize=12)
ax.set_ylabel('Number of Nodes', fontsize=12)
ax.set_title('Degree Distribution of Kronecker Graph', fontsize=14, fontweight='bold')
ax.grid(True, alpha=0.3)

# Informative annotation (corrected from power-law claim)
ax.annotate('Broad degree distribution\n(characteristic of Kronecker graphs)', 
            xy=(max(degrees_plot), max(counts_plot)), 
            xytext=(max(degrees_plot)*0.6, max(counts_plot)*0.7),
            arrowprops=dict(arrowstyle='->', color='red'),
            fontsize=10, color='red')

plt.tight_layout()
plt.show()

# ==========================================================
# SECTION 12: SUMMARY
# ==========================================================

print("\n" + "="*70)
print("SUMMARY: KRONECKER GRAPHS IN NETWORK SCIENCE")
print("="*70)

summary_points = [
    "✓ Kronecker product creates self-similar graphs",
    "✓ Small initiator matrix (2×2) generates larger networks",
    "✓ Degree distribution shows broad distribution",
    "✓ Properties resemble real-world networks:",
    "  - Social networks",
    "  - Communication networks",
    "  - Internet topology",
    "  - Biological networks",
    "✓ Stochastic version uses probabilities instead of binary values",
    "✓ Fast generation algorithms achieve O(E) for large graphs"
]

for point in summary_points:
    print(point)

print("\n" + "="*70)
print("EXERCISE 5B COMPLETE ✓")
print("="*70)
